using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using plate.wtf.Core.Plates.Interfaces;
using plate.wtf.Models;
using plate.wtf.Models.Constants;

namespace plate.wtf.Core.Plates
{
    public class DePlate : IDePlate
    {
        private static string Standard1956Regex = @"^(([A-Z|Ü|Ö]{1,3})-([A-Z]{1,2})\s?([0-9]{1,4}))$";
        private static string Standard1956ElectricRegex = @"^(([A-Z|Ü|Ö]{1,3})-\s?([0-9]{1,4})([E]))$";
        private static string Diplomatic1956Regex = @"^(([0]{1})-([0-9]{1,3})-([0-9]{1,3}))$";
    
        public Plate Parse(string plate)
        {
            Plate plateReturn = new Plate {};

            if(Regex.IsMatch(plate, Standard1956Regex))
            {
                plateReturn.Info = ParseStandard1956Plate(plate);
                plateReturn.Valid = true;
            }
            else if(Regex.IsMatch(plate, Standard1956ElectricRegex))
            {
                plateReturn.Info = ParseStandard1956Plate(plate, true);
                plateReturn.Valid = true;
            }
            else if(Regex.IsMatch(plate, Diplomatic1956Regex))
            {
                Enums.PlateFormat plateFormat = Enums.PlateFormat.De_Diplomatic1956;

                plateReturn.Info = new PlateInfo
                {
                    Format = EnumConstants.GetPlateFormatConstant(plateFormat),
                    FormatEnum = plateFormat
                };
                plateReturn.Valid = true;
            }
            else
            {
                plateReturn.Valid = false;
            }

            plateReturn.Country = new Country
            {
                Code = "de",
                Flag = "🇩🇪"
            };

            plateReturn.Serial = plate;

            return plateReturn;
        }

        private static PlateInfo ParseStandard1956Plate(string plate, bool electricSpecial = false)
        {
            string regionOrSpecial = null;
            string regionString = null;
            string specialString = null;

            if(!electricSpecial)
            {
                Regex regex = new Regex(Standard1956Regex);
                Match match = regex.Match(plate);

                regionOrSpecial = match.Groups[2].Value;
            }
            else
            {
                Regex regex = new Regex(Standard1956Regex);
                Match match = regex.Match(plate);

                regionOrSpecial = match.Groups[2].Value;
            }

            Enums.PlateFormat plateFormat = Enums.PlateFormat.De_Standard1956;

            PlateInfo returnModel = new PlateInfo
            {
                Format = EnumConstants.GetPlateFormatConstant(plateFormat),
                FormatEnum = plateFormat,
                Region = null,
                Special = null
            };

            if(Post1956SpecialCodes.ContainsKey(regionOrSpecial))
            {
                Post1956SpecialCodes.TryGetValue(regionOrSpecial, out specialString);
                returnModel.Special = specialString;
            }
            else if(Post1956LocationCodes.ContainsKey(regionOrSpecial))
            {
                Post1956LocationCodes.TryGetValue(regionOrSpecial, out regionString);
                returnModel.Region = regionString;
            }

            if(electricSpecial) {
                returnModel.Special = "Electric Vehicle";
            }

            return returnModel;
        }

        private static Dictionary<string, string> Post1956SpecialCodes = new Dictionary<string, string>()
        {
            {"0", "Diplomatic"},
            {"AD", "US Military"},
            {"BD", "Federal Goverment"},
            {"BG", "Border Police"},
            {"BP", "Postal Authority"},
            {"BW", "Maritime Authority"},
            {"DB", "Rail Authority"},
            {"THW", "German Federal Agency"},
            {"X", "NATO Forces"},
            {"Y", "Armed Forces"},
            {"BBL", "Brandenburd Land Official"},
            {"BWL", "Badem-Württemberg Land Official"},
            {"BYL", "Bavaria State (Bayern Land) Official"},
            {"HEL", "Hesse State (Hesse Land) Official"},
            {"LSA", "Saxony Anhalt State (Sachsen-Anhalt Land) Official"},
            {"LSN", "Saxony State (Sachsen Land) Official"},
            {"MVL", "Mecklenburg-Vorpommern Land Official"},
            {"NL", "Lower Saxony State (Niedersachsen Land) Official"},
            {"NRW", "North-Rhine-Westphalia State (Nordrhein-Westfalen Land) Official"},
            {"RPL", "Rhineland Palatinate State (Rheinland-Pfalz Land) Official"},
            {"RWL", "North-Rhine-Westphalia State (Nordrhein-Westfalen Land) Official"},
            {"SAL", "Saarland Official"},
            {"SH", "Schleswig-Holstein Land Official"},
            {"THL", "Thuringia State (Thüringen Land) Official"}
        };

        private static Dictionary<string, string> Post1956LocationCodes = new Dictionary<string, string>()
        {
            {"A", "Augsburg, Bavaria"},
            {"AA", "Aalen & Ostalbkreis, Baden-Württemberg"},
            {"AB", "Aschaffenburg, Bavaria"},
            {"ABG", "Altenburger Land, Thuringia"},
            {"AC", "Aachen, North-Rhine-Westphalia"},
            {"AH", "Ahaus, North-Rhine-Westphalia"},
            {"AIB", "Bad Aibling, Bavaria"},
            {"AIC", "Aichach-Friedberg, Bavaria"},
            {"AE", "Auerbach, Saxony"},
            {"AK", "Altenkirchen (Westerwald), Rhineland Palatinate"},
            {"AL", "Altena, North-Rhine-Westphalia"},
            {"ALF", "Alfeld, Lower Saxony"},
            {"ALS", "Alsfeld, Hesse"},
            {"ALZ", "Alzenau, Bavaria"},
            {"AM", "Amberg, Bavaria"},
            {"AN", "Ansbach, Bavaria"},
            {"ANA", "Annaberg-Buchholz, Saxony"},
            {"ANG", "Angermünde, Brandenburg"},
            {"ANK", "Anklam, Mecklenburg-Vorpommern"},
            {"AÖ", "Altötting, Bavaria"},
            {"AP", "Apolda & Weimarer Land, Thuringia"},
            {"APD", "Apolda, Thuringia"},
            {"AR", "Arnsberg, North-Rhine-Westphalia"},
            {"ARN", "Arnstadt, Thuringia"},
            {"ART", "Artern, Thuringia"},
            {"AS", "Amberg-Sulzbach, Bavaria"},
            {"ASD", "Aschendorf, Lower Saxony"},
            {"ASL", "Aschersleben-Staßfurter Landkreis, Saxony-Anhalt"},
            {"ASZ", "Aue-Schwarzenberg, Saxony"},
            {"AT", "Alten-Treptow, Mecklenburg-Vorpommern"},
            {"AU", "Aue, Saxony"},
            {"AUR", "Aurich, Lower Saxony"},
            {"AW", "Ahrweiler, Rhineland Palatinate"},
            {"AZ", "Alzey-Worms, Rhineland Palatinate"},
            {"AZE", "Anhalt-Zerbst, Saxony-Anhalt"},
            {"B", "Berlin"},
            {"BA", "Bamberg, Bavaria"},
            {"BAD", "Baden-Baden, Baden-Württemberg"},
            {"BAR", "Barnim (Eberswalde), Brandenburg"},
            {"BB", "Böblingen, Baden-Württemberg"},
            {"BBG", "Bernburg, Saxony-Anhalt"},
            {"BC", "Biberach, Baden-Württemberg"},
            {"BCH", "Buchen, Baden-Württemberg"},
            {"BD", "Federal German government vehicles"},
            {"BE", "Bechum, North-Rhine-Westphalia"},
            {"BED", "Brand-Erbisdorf, Saxony"},
            {"BEI", "Beilingries, Bavaria"},
            {"BEL", "Blezig, Brandenburg"},
            {"BER", "Bernau, Brandenburg"},
            {"BF", "Burgsteinfurt, North-Rhine-Westphalia"},
            {"BG", "Border police vehicles"},
            {"BGD", "Berchtesgaden, Bavaria"},
            {"BGL", "Berchtesgardener Land, Bavaria"},
            {"BH", "Bühl, Baden-Württenmberg"},
            {"BI", "Bielefeld, North-Rhine-Westphalia"},
            {"BID", "Biedenkopf, Hesse"},
            {"BIN", "Bingen, Rhineland Palatinate"},
            {"BIR", "Birkenfeld, Rhineland Palatinate"},
            {"BIT", "Bitburg-Prüm, Rhineland Palatinate"},
            {"BIW", "Bischofswerda, Saxony"},
            {"BK", "Bicknang, Baden-Württemberg"},
            {"BKS", "Bernkastel, Rhineland Palatinate"},
            {"BL", "Balingen & Zollernalbkreis, Baden-Württemberg"},
            {"BLB", "Bad Berleburg, North-Rhine-Westphalia"},
            {"BLK", "Burgenlandkreis, Saxony-Anhalt"},
            {"BM", "Bergheim & Erftkreis, North-Rhine-Westphalia"},
            {"BN", "Bonn, North-Rhine-Westphalia"},
            {"BNA", "Borna, Saxony"},
            {"BO", "Bochum, North-Rhine-Westphalia"},
            {"BÖ", "Bördekreis, Saxony-Anhalt"},
            {"BOG", "Bogen, Bavaria"},
            {"BOH", "Bocholt, North-Rhine-Westphalia"},
            {"BOR", "Borken, North-Rhine-Westphalia"},
            {"BOT", "Bottrop, North-Rhine-Westphalia"},
            {"BP", "Postal authority vehicles (Bundespost)"},
            {"BR", "Bruchsal, Baden-Württemberg"},
            {"BRA", "Brake (Unterweser) & Wesermarsch, Lower Saxony"},
            {"BRB", "Brandenburg, Brandenburg"},
            {"BRG", "Burg, Saxony-Anhalt"},
            {"BRI", "Brilon, North-Rhine-Westphalia"},
            {"BRK", "Bad Brückenau, Bavaria"},
            {"BRL", "Braunlage, Lower Saxony"},
            {"BRV", "Bremervörde, Lower Saxony"},
            {"BS", "Brunswick (Braunschweig), Lower Saxony"},
            {"BSB", "Bersenbrück, Lower Saxony"},
            {"BSK", "Beeskow, Brandenburg"},
            {"BT", "Bayreuth, Bavaria"},
            {"BTF", "Bitterfeld, Saxony-Anhalt"},
            {"BU", "Burgdorf, Lower Saxony"},
            {"BÜD", "Büdingen, Hesse"},
            {"BUL", "Burglengenfeld, Bavaria"},
            {"BUR", "Buren, North-Rhine-Westphalia"},
            {"BÜS", "Büsingen & Konstanz, Baden-Württemberg"},
            {"BÜZ", "Bützow, Mecklenburg-Vorpommern"},
            {"BW", "Maritime authority vehicles"},
            {"BWL", "Badem-Württemberg Land official vehicles"},
            {"BYL", "Bavaria State (Bayern Land) official vehicles"},
            {"BZ", "Bautzen, Saxony"},
            {"BZA", "Bergzabern, Rhineland Palatinate"},
            {"C", "Chemnitz, Saxony"},
            {"CA", "Calau, Brandenburg"},
            {"CAS", "Castrop-Rauxel, North-Rhine-Westphalia"},
            {"CB", "Cottbus, Brandenburg"},
            {"CE", "Celle, Lower Saxony"},
            {"CHA", "Cham, Bavaria"},
            {"CHL", "Chemnitzer Land, Kreis Glochau, Saxony"},
            {"CLP", "Cloppenburg, Lower Saxony"},
            {"CLZ", "Clausthal-Zellerfeld, Lower Saxony"},
            {"CO", "Coburg, Bavaria"},
            {"COC", "Cochem-Zell, Rhineland Palatinate"},
            {"COE", "Coesfeld, North-Rhine-Westphalia"},
            {"CR", "Crailsheim, Baden-Württemberg"},
            {"CT", "Cottbus, Saxony"},
            {"CUX", "Cuxhaven, Lower Saxony"},
            {"CW", "Calw, Baden-Württemberg"},
            {"D", "Düsseldorf, North-Rhine-Westphalia"},
            {"DA", "Darmstadt & Darmstadt-Dieburg, Hesse"},
            {"DAH", "Dachau, Bavaria"},
            {"DAN", "Lüchow-Dannenberg, Lower Saxony"},
            {"DAU", "Daun, Rhineland Palatinate"},
            {"DB", "Rail authority vehicles (Deutsche Bundesbahn)"},
            {"DBR", "Bad Doberan, Mecklenburg-Vorpommern"},
            {"DD", "Dresden"},
            {"DE", "Dessau, Saxony-Anhalt"},
            {"DEG", "Deggendorf, Bavaria"},
            {"DEL", "Delmenhorst, Lower Saxony"},
            {"DG", "Donaueschingen, Baden-Württemberg"},
            {"DGF", "Dingolfing-Landau, Bavaria"},
            {"DH", "Diepholz, Lower Saxony"},
            {"DI", "Dieburg, Hesse"},
            {"DIL", "Dillenburg, Hesse"},
            {"DIN", "Dinslaken, North-Rhine-Westphalia"},
            {"DIZ", "Diez, Rhineland Palatinate"},
            {"DKB", "Dinkelsbühl, Bavaria"},
            {"DL", "Döbeln, Saxony"},
            {"DLG", "Dillingen an der Donau, Bavaria"},
            {"DM", "Demmin, Mecklenburg-Vorpommern"},
            {"DN", "Düren, North-Rhine-Westphalia"},
            {"DO", "Dortmund, North-Rhine-Westphalia"},
            {"DON", "Donau-Ries, Bavaria"},
            {"DS", "Donaueschingen, Baden-Württemberg"},
            {"DT", "Detmold & Lippe, North-Rhine-Westphalia"},
            {"DU", "Duisburg, North-Rhine-Westphalia"},
            {"DUD", "Duderstadt, Lower Saxony"},
            {"DÜW", "Bad Dürkheim & Weinstraße, Rhineland Palatinate"},
            {"DW", "Dippoldiswalde & Weißeritzkreis, Saxony"},
            {"DZ", "Delitzsch, Saxony"},
            {"E", "Essen, North-Rhine-Westphalia"},
            {"EA", "Eisenach, Thuringia"},
            {"EB", "Eilenburg, Saxony"},
            {"EBE", "Ebersberg, Bavaria"},
            {"EBN", "Ebern, Bavaria"},
            {"EBS", "Ebermannstadt, Bavaria"},
            {"ECK", "Eckernförde, Schleswig-Holstein"},
            {"ED", "Erding, Bavaria"},
            {"EE", "Elbe-Elster, Brandenburg"},
            {"EF", "Erfurt, Thuringia"},
            {"EG", "Eggenfelden, Bavaria"},
            {"EH", "Eisenhüttenstadt, Brandenburg"},
            {"EHI", "Ehingen, Baden-Württemberg"},
            {"EI", "Eichstätt, Bavaria"},
            {"EIC", "Eichsfeld, Thuringia"},
            {"EIH", "Eichstätt, Bavaria"},
            {"EIL", "Eisleben, Saxony-Anhalt"},
            {"EIN", "Einbeck, Lower Saxony"},
            {"EIS", "Eisenberg"},
            {"EL", "Emsland, Lower Saxony"},
            {"EM", "Emmendingen, Baden-Württemberg"},
            {"EMD", "Emden, Lower Saxony"},
            {"EMS", "Bad Ems & Rhein-Lahn-Kreis, Rhineland Palatinate"},
            {"EN", "Ennepe-Ruhr-Kreis, North-Rhine-Westphalia"},
            {"ER", "Erlangen, Bavaria"},
            {"ERB", "Erbach & Oldenwaldkreis, Hesse"},
            {"ERH", "Erlangen-Höchstadt, Bavaria"},
            {"ERK", "Erkelenz, North-Rhine-Westphalia"},
            {"ES", "Esslingen, Baden-Württemberg"},
            {"ESA", "Eisenach, Thuringia"},
            {"ESB", "Eschenbach, Bavaria"},
            {"ESW", "Eschwege & Werra-Meißner-Kreis, Hesse"},
            {"EU", "Euskirchen, North-Rhine-Westphalia"},
            {"EUT", "Eutin, Schleswig-Holstein"},
            {"EW", "Eberswalde, Brandenburg"},
            {"F", "Frankfurt am Main, Hesse"},
            {"FAL", "Fallingbostel, North-Rhine-Westphalia"},
            {"FB", "Friedberg (Hessen) & Wetteraukreis, Hesse"},
            {"FD", "Fulda, Hesse"},
            {"FDB", "Friedberg bei Augsburg, Bavaria"},
            {"FDS", "Freudenstadt, Baden-Württemberg"},
            {"FEU", "Feuchtwangen, Bavaria"},
            {"FF", "Frankfurt-an-der-Oder, Brandenburg"},
            {"FFB", "Fürstenfeldbruck, Bavaria"},
            {"FG", "Freiberg, Saxony"},
            {"FH", "Frankfurt am Main/Höchst, Hesse"},
            {"FI", "Finsterwalde, Brandenburg"},
            {"FKB", "Frankenberg, Hesse"},
            {"FL", "Flensburg, Schleswig-Holstein"},
            {"FLÖ", "Flöha, Saxony"},
            {"FN", "Friedrichshafen & Bodenseekreis, Baden-Württemberg"},
            {"FO", "Forchheim, Bavaria"},
            {"FOR", "Forst, Brandenburg"},
            {"FR", "Freiburg im Breisgau & Breisgau-Hochschwarzwald, Baden-Württemberg"},
            {"FRG", "Freyung-Grafenau, Bavaria"},
            {"FRI", "Friesland, Lower Saxony"},
            {"FRW", "Bad Freienwalde, Brandenburg"},
            {"FS", "Freising, Bavaria"},
            {"FT", "Frankenthal (Pfalz), Rhineland Palatinate"},
            {"FTL", "Freital, Saxony"},
            {"FÜ", "Fürth, Bavaria"},
            {"FÜS", "Füssen, Bavaria"},
            {"FW", "Fürstenwalde, Brandenburg"},
            {"FZ", "Fritzlar, Hesse"},
            {"G", "Gera, Thuringia"},
            {"GA", "Gardelegen, Saxony Anhalt"},
            {"GAN", "Bad Gandersheim, Lower Saxony"},
            {"GAP", "Garmisch-Partenkirchen, Bavaria"},
            {"GC", "Glauchau & Chemnitzer Land, Saxony"},
            {"GD", "Gmünd, Baden-Württemberg"},
            {"GDB", "Gadesbusch, Mecklenburg-Vorpommern"},
            {"GE", "Gelsenkirchen, North-Rhine-Westphalia"},
            {"GEL", "Geldern, North-Rhine-Westphalia"},
            {"GEM", "Gemünden, Bavaria"},
            {"GEO", "Gerolzhofen, Bavaria"},
            {"GER", "Germersheim, Rhineland Palatinate"},
            {"GF", "Gifhorn, Lower Saxony"},
            {"GG", "Groß-Gerau, Hesse"},
            {"GHA", "Geithain, Saxony"},
            {"GHC", "Gräfenhainichen, Saxony Anhalt"},
            {"GI", "Gießen, Hesse"},
            {"GK", "Geilenkirchen, North-Rhine-Westphalia"},
            {"GL", "Bergisch-Gladbach & Rheinisch-Bergischer Kreis, North-Rhine-Westphalia"},
            {"GLA", "Gladbeck, North-Rhine-Westphalia"},
            {"GM", "Gummersbach & Oberbergischer Kreis, North-Rhine-Westphalia"},
            {"GMN", "Grimmen, Mecklenburg-Vorpommern"},
            {"GN", "Gelnhausen, Hesse"},
            {"GNT", "Genthin, Saxony Anhalt"},
            {"GÖ", "Göttingen, Lower Saxony"},
            {"GOA", "St Goar, Rheinland Palatinate"},
            {"GOH", "St Goarshausen, Rheinland Palatinate"},
            {"GP", "Göppingen, Baden-Württemberg"},
            {"GR", "Görlitz, Saxony"},
            {"GRA", "Grafenau, Bavaria"},
            {"GRH", "Grossenheim"},
            {"GRI", "Griesbach, Bavaria"},
            {"GRM", "Grimma, Saxony"},
            {"GRS", "Gransee, Brandenburg"},
            {"GRZ", "Greiz, Thuringia"},
            {"GS", "Goslar, Lower Saxony"},
            {"GT", "Gütersloh, North-Rhine-Westphalia"},
            {"GTH", "Gotha, Thuringia"},
            {"GÜ", "Güstrow, Mecklenburg-Vorpommern"},
            {"GUB", "Guben, Brandenburg"},
            {"GUN", "Gunzenhausen, Bavaria"},
            {"GV", "Gravenbroich, North-Rhine-Westphalia"},
            {"GVM", "Grevesmühlen, Mecklenburg-Vorpommern"},
            {"GW", "Greifswald Land, Mecklenburg-Vorpommern"},
            {"GZ", "Günzburg, Bavaria"},
            {"H", "Hanover (Hannover), Lower Saxony"},
            {"HA", "Hagen, North-Rhine-Westphalia"},
            {"HAB", "Hammelburg, Bavaria"},
            {"HAL", "Halle, Saxony-Anhalt"},
            {"HAM", "Hamm, North-Rhine-Westphalia"},
            {"HAS", "Haßberge, Bavaria"},
            {"HB", "Hansestadt Bremen"},
            {"HBN", "Hildburghausen, Thuringia"},
            {"HBS", "Halberstadt, Saxony-Anhalt"},
            {"HC", "Hainichen, Saxony"},
            {"HCH", "Hechingen, Baden-Württemberg"},
            {"HD", "Heidelberg & Rhein-Neckar-Kreis, Baden-Württemberg"},
            {"HDH", "Heidenheim, Baden-Württemberg"},
            {"HDL", "Haldensleben, Saxony Anhalt"},
            {"HE", "Helmstedt, Lower Saxony"},
            {"HEB", "Hersbruck, Bavaria"},
            {"HEF", "Hersfeld-Rotenburg, Hesse"},
            {"HEI", "Heide & Dithmarschen, Schleswig-Holstein"},
            {"HEL", "Hesse State (Hesse Land) official vehicles"},
            {"HER", "Herne, North-Rhine-Westphalia"},
            {"HET", "Hettstedt, Saxony Anhalt"},
            {"HF", "Herford, North-Rhine-Westphalia"},
            {"HG", "Bad Homburg vor der Höhe & Hochtaunuskreis, Hesse"},
            {"HGN", "Hagenow, Mecklenburg-Vorpommern"},
            {"HGW", "Hansestadt Greifswald, Mecklenburg-Vorpommern"},
            {"HH", "Hansestadt Hamburg"},
            {"HHM", "Hohenmölsen, Saxony Anhalt"},
            {"HI", "Hildesheim, Lower Saxony"},
            {"HIG", "Heiligenstadt, Thuringia"},
            {"HIP", "Hilpoltstein, Bavaria"},
            {"HK", "Heidekreis, Lower Saxony"},
            {"HL", "Hansestadt Lübeck"},
            {"HM", "Hamelin(Hameln)-Pyrmont, Lower Saxony"},
            {"HMU", "Hanoversch Münden, Lower Saxony"},
            {"HN", "Heilbronn, Baden-Württemberg"},
            {"HO", "Hof, Bavaria"},
            {"HOG", "Hofgeismar, Hesse"},
            {"HOH", "Hofheim, Bavaria"},
            {"HOL", "Holzminden, Lower Saxony"},
            {"HOM", "Homburg & Saar-Pfalz-Kreis, Saarland"},
            {"HOR", "Horb, Baden-Württemberg"},
            {"HÖS", "Höchstadt, Bavaria"},
            {"HOT", "Hohenstein-Ernstthal, Saxony"},
            {"HP", "Heppenheim an der Bergstraße & Bergstraße, Hesse"},
            {"HR", "Homberg & Schwalm-Eder-Kreis, Hesse"},
            {"HRO", "Hansestadt Rostock, Mecklenburg-Vorpommern"},
            {"HS", "Heinsberg, North-Rhine-Westphalia"},
            {"HSK", "Hochsauerlandkreis, North-Rhine-Westphalia"},
            {"HST", "Hansestadt Stralsund, Mecklenburg-Vorpommern"},
            {"HU", "Hanau & Main-Kinzig-Kreis, Hesse"},
            {"HÜN", "Hünfeld, Schleswig-Holstein"},
            {"HUS", "Husum, Schleswig-Holstein"},
            {"HV", "Havelberg, Saxony Anhalt"},
            {"HVL", "Havelland, Brandenburg"},
            {"HW", "Halle Westfalen, North-Rhine-Westphalia"},
            {"HWI", "Hansestadt Wismar, Mecklenburg-Vorpommern"},
            {"HX", "Höxter, North-Rhine-Westphalia"},
            {"HY", "Hoyerswerda, Saxony"},
            {"HZ", "Herzberg, Brandenburg"},
            {"IGB", "Stadt St Ingbert & Saar-Pfalz-Kreis, Saarland"},
            {"IK", "Ilm-Kreis, Thuringia"},
            {"IL", "Ilmenau, Thuringia"},
            {"ILL", "Illertissen, Bavaria"},
            {"IN", "Ingolstadt, Bavaria"},
            {"IS", "Iserlohn, North-Rhine-Westphalia"},
            {"IZ", "Itzehoe & Steinburg, Schleswig-Holstein"},
            {"J", "Jena, Thuringia"},
            {"JB", "Jüterbog, Brandenburg"},
            {"JE", "Jessen, Saxony Anhalt"},
            {"JEV", "Jever, Lower Saxony"},
            {"JL", "Jerichower Land, Saxony-Anhalt"},
            {"JÜL", "Jülich, North-Rhine-Westphalia"},
            {"K", "Cologne (Köln), North-Rhine-Westphalia"},
            {"KA", "Karlsruhe, Baden-Württemberg"},
            {"KAR", "Karlstadt, Bavaria"},
            {"KB", "Korbach & Waldeck-Frankenberg, Hesse"},
            {"KC", "Kronach, Bavaria"},
            {"KE", "Kempten (Allgäu), Bavaria"},
            {"KEH", "Kelheim, Bavaria"},
            {"KEL", "Kehl, Baden-Württemberg"},
            {"KEM", "Kemnath, Bavaria"},
            {"KF", "Kaufbeuren, Bavaria"},
            {"KG", "Bad Kissingen, Bavaria"},
            {"KH", "Bad Kreuznach, Rhineland Palatinate"},
            {"KI", "Kiel, Schleswig-Holstein"},
            {"KIB", "Kirchheimbolanden & Donnersbergkreis, Rhineland Palatinate"},
            {"KK", "Kempen-Krefeld, North-Rhine-Westphalia"},
            {"KL", "Kaiserslauten, Rhineland Palatinate"},
            {"KLE", "Cleves (Kleve), North-Rhine-Westphalia"},
            {"KLT", "Klingental, Saxony"},
            {"KLZ", "Klötze, Saxony Anhalt"},
            {"KM", "Kamenz, Saxony"},
            {"KN", "Constance (Konstanz), Baden-Württemberg"},
            {"KO", "Koblenz, Rhineland Palatinate"},
            {"KÖN", "Kötzting, Bavaria"},
            {"KÖT", "Köthen, Saxony-Anhalt"},
            {"KOZ", "Kotzting"},
            {"KR", "Krefeld, North-Rhine-Westphalia"},
            {"KRU", "Krumbach, Bavaria"},
            {"KS", "Kassel, Hesse"},
            {"KT", "Kitzingen, Bavaria"},
            {"KU", "Kulmbach, Bavaria"},
            {"KÜN", "Küzelsau & Hohenlohekreis, Baden-Württemberg"},
            {"KUS", "Kusel, Rhineland Palatinate"},
            {"KW", "Königs-Wusterhausen, Brandenburg"},
            {"KY", "Kyritz, Brandenburg"},
            {"KYF", "Kyffhäuserkreis, Thuringia"},
            {"L", "Leipzig, Saxony"},
            {"LA", "Landshut, Bavaria"},
            {"LAN", "Landau Isar, Bavaria"},
            {"LAT", "Lauterbach, Hesse"},
            {"LAU", "Lauf an der Pegnitz & Nürnberger Land, Bavaria"},
            {"LB", "Ludwigsburg, Baden-Württemberg"},
            {"LBS", "Lobenstein, Thuringia"},
            {"LBZ", "Lübz, Mecklenburg-Vorpommern"},
            {"LC", "Luckau, Brandenburg"},
            {"LD", "Landau in der Pfalz, Rhineland Palatinate"},
            {"LDK", "Lahn-Dill-Kreis, Hesse"},
            {"LDS", "Landkreis Dahme-Spreewald, Brandenburg"},
            {"LE", "Lemgo, North-Rhine-Westphalia"},
            {"LEO", "Leonberg, Baden-Württemberg"},
            {"LER", "Leer (Ostfriesland), Lower Saxony"},
            {"LEV", "Leverkusen, North-Rhine-Westphalia"},
            {"LF", "Laufen, Bavaria"},
            {"LG", "Lüneburg, Lower Saxony"},
            {"LH", "Lüdinghausen, North-Rhine-Westphalia"},
            {"LI", "Lindau (Bodensee), Bavaria"},
            {"LIB", "Bad Liebenwerda, Brandenburg"},
            {"LIF", "Lichtenfels, Bavaria"},
            {"LIN", "Lingen, Lower Saxony"},
            {"LIP", "Lippe, North-Rhine-Westphalia"},
            {"LK", "Lübbecke, North-Rhine-Westphalia"},
            {"LL", "Landsberg am Lech, Bavaria"},
            {"LM", "Limburg-Weilburg, Hesse"},
            {"LN", "Lübben, Brandenburg"},
            {"LÖ", "Lörrach, Baden-Württemberg"},
            {"LÖB", "Löbau, Saxony"},
            {"LOH", "Lohr am Main, Bavaria"},
            {"LOS", "Landkreis Oder-Spree, Brandenburg"},
            {"LP", "Lippstadt, North-Rhine-Westphalia"},
            {"LR", "Lahr, Baden-Württemberg"},
            {"LS", "Lüdenscheid, North-Rhine-Westphalia"},
            {"LSA", "Saxony Anhalt State official vehicles"},
            {"LSN", "Saxony State official vehicles"},
            {"LSZ", "Bad Langensalza, Thuringia"},
            {"LU", "Ludwigshafen am Rhein, Rhineland Palatinate"},
            {"LÜD", "Lüdenscheid, North-Rhine-Westphalia"},
            {"LUK", "Luckenwalde, Brandenburg"},
            {"LÜN", "Lünen, North-Rhine-Westphalia"},
            {"LWL", "Ludwigslust, Mecklenburg-Vorpommern"},
            {"M", "Munich (München), Bavaria"},
            {"MA", "Mannheim, Baden-Württemberg"},
            {"MAB", "Marienberg, Saxony"},
            {"MAI", "Mainburg, Bavaria"},
            {"MAK", "Marktredwitz, Bavaria"},
            {"MAL", "Mallersdorf, Bavaria"},
            {"MAR", "Marktheidenfeld, Bavaria"},
            {"MB", "Miesbach, Bavaria"},
            {"MC", "Malchin, Mecklenburg-Vorpommern"},
            {"MD", "Magdeburg, Saxony-Anhalt"},
            {"ME", "Mettmann, North-Rhine-Westphalia"},
            {"MED", "Meldorf, Schleswig-Holstein"},
            {"MEG", "Melsungen, Hesse"},
            {"MEI", "Meissen, Saxony"},
            {"MEK", "Mittlerer Erzgebirgskreis, Saxony"},
            {"MEL", "Melle, Lower Saxony"},
            {"MEP", "Meppen, Lower Saxony"},
            {"MER", "Merseburg, Saxony Anhalt"},
            {"MES", "Meschede, North-Rhine-Westphalia"},
            {"MET", "Mellrichstadt, Bavaria"},
            {"MG", "Mönchengladbach, North-Rhine-Westphalia"},
            {"MGH", "Bad Mergentheim, Baden-Württemberg"},
            {"MGN", "Meiningen, Thuringia"},
            {"MH", "Mülheim an der Ruhr, North-Rhine-Westphalia"},
            {"MHL", "Mühlhausen"},
            {"MI", "Minden-Lübbecke, North-Rhine-Westphalia"},
            {"MIL", "Miltenberg, Bavaria"},
            {"MK", "Märkischer Kreis, North-Rhine-Westphalia"},
            {"MKK", "Main-Kinzig-Kreis, Hessen"},
            {"ML", "Mansfelder Land, Saxony-Anhalt"},
            {"MM", "Memmingen, Bavaria"},
            {"MN", "Mindelheim & Unterallgäu, Bavaria"},
            {"MO", "Moers, North-Rhine-Westphalia"},
            {"MOD", "Marktoberdorf, Bavaria"},
            {"MOL", "Märkisch-Oderland, Brandenburg"},
            {"MON", "Monschau, North-Rhine-Westphalia"},
            {"MOS", "Mosbach & Neckar-Odenwald-Kreis, Baden-Württemberg"},
            {"MQ", "Merseburg-Querfurt, Saxony-Anhalt"},
            {"MR", "Marburg-Biedenkopf, Hesse"},
            {"MS", "Münster, North-Rhine-Westphalia"},
            {"MSP", "Main-Spessart-Kreis, Bavaria"},
            {"MST", "Mecklenburg-Strelitz, Mecklenburg-Vorpommern"},
            {"MT", "Montabaur, Rhineland Palatinate"},
            {"MTK", "Main-Taunus-Kreis, Hesse"},
            {"MTL", "Muldentalkreis, Saxony"},
            {"MÜ", "Mühldorf am Inn, Bavaria"},
            {"MÜB", "Münchberg, Bavaria"},
            {"MÜL", "Müllheim, Baden-Württemberg"},
            {"MÜN", "Münsingen, Baden-Württemberg"},
            {"MÜR", "Müritz, Mecklenburg-Vorpommern"},
            {"MVL", "Mecklenburg-Vorpommern Land official vehicles"},
            {"MW", "Mittweida, Saxony"},
            {"MY", "Mayen, Rhineland Palatinate"},
            {"MYK", "Mayen-Koblenz, Rhineland Palatinate"},
            {"MZ", "Mainz & Mainz-Bingen, Rhineland Palatinate"},
            {"MZG", "Merzig-Wadern, Saarland"},
            {"N", "Nuremberg (Nürnberg), Bavaria"},
            {"NAB", "Nabburg, Bavaria"},
            {"NAI", "Naila, Bavaria"},
            {"NAU", "Nauen, Brandenburg"},
            {"NB", "Neubrandenburg, Mecklenburg-Vorpommern"},
            {"ND", "Neuberg an der Donau & Neuberg-Schrobenhausen, Bavaria"},
            {"NDH", "Nordhausen, Thuringia"},
            {"NE", "Neuss, North-Rhine-Westphalia"},
            {"NEA", "Neustadt an der Aisch & Bad Windsheim, Bavaria"},
            {"NEB", "Nebra, Saxony Anhalt"},
            {"NEC", "Neustadt Coburg, Bavaria"},
            {"NEN", "Neunburg, Bavaria"},
            {"NES", "Bad Neustadt an der Saale & Rhön-Grabfeld, Bavaria"},
            {"NEU", "Neustadt Schwarzwald, Baden-Württemberg"},
            {"NEW", "Neustadt an der Waldnaab, Bavaria"},
            {"NF", "Nordfriesland, Schleswig-Holstein"},
            {"NH", "Neuhaus an der Rennweg, Thuringia"},
            {"NI", "Nienberg (Weser), Lower Saxony"},
            {"NIB", "Niebüll, Schleswig-Holstein"},
            {"NK", "Neunkirchen/Saar, Saarland"},
            {"NL", "Lower Saxony State official vehicles"},
            {"NM", "Neumarkt in der Oberpfalz, Bavaria"},
            {"NMB", "Naumberg, Saxony Anhalt"},
            {"NMS", "Neumünster, Schleswig-Holstein"},
            {"NÖ", "Nördlingen, Bavaria"},
            {"NOH", "Nordhorn & Grafschaft Bentheim, Lower Saxony"},
            {"NOL", "Niederschlesischer Oberlausitzkreis, Saxony"},
            {"NOM", "Northeim, Lower Saxony"},
            {"NOR", "Norden, Lower Saxony"},
            {"NP", "Neuruppin, Brandenburg"},
            {"NR", "Neuwied am Rhein, Rhineland Palatinate"},
            {"NRÜ", "Neustadt am Rübenberge, Lower Saxony"},
            {"NRW", "North-Rhine-Westphalia State official vehicles"},
            {"NU", "Neu-Ulm, Bavaria"},
            {"NT", "Nürtingen, Baden-Württemberg"},
            {"NVP", "Nordvorpommern, Mecklenburg-Vorpommern"},
            {"NW", "Neustadt an der Weinstraße, Rhineland Palatinate"},
            {"NWM", "Nordwestmecklenburg, Mecklenburg-Vorpommern"},
            {"NY", "Niesky, Saxony"},
            {"NZ", "Neustrelitz, Mecklenburg-Vorpommern"},
            {"OA", "Oberallgäu, Bavaria"},
            {"OAL", "Ostallgäu, Bavaria"},
            {"OB", "Oberhausen, North-Rhine-Westphalia"},
            {"OBB", "Obernburg, Bavaria"},
            {"OBG", "Osterburg, Saxony Anhalt"},
            {"OC", "Oschersleben, Saxony"},
            {"OCH", "Ochsenfurt, Bavaria"},
            {"OD", "Bad Oldesloe & Stormarn, Schleswig-Holstein"},
            {"OE", "Olpe, North-Rhine-Westphalia"},
            {"OF", "Offenbach am Main, Hesse"},
            {"OG", "Offenburg & Ortenaukreis, Baden-Württemberg"},
            {"OH", "Ostholstein, Schleswig-Holstein"},
            {"OHA", "Osterode am Harz, Lower Saxony"},
            {"ÖHR", "Öhringen, Baden-Württemberg"},
            {"OHV", "Oberhavel, Brandenburg"},
            {"OHZ", "Osterholz, Lower Saxony"},
            {"OK", "Ohre-Kreis, Saxony-Anhalt"},
            {"OL", "Oldenburg, Lower Saxony"},
            {"OLD", "Oldenburg (Holstein), Schleswig-Holstein"},
            {"OP", "Opladen, North-Rhine-Westphalia"},
            {"OPR", "Ostprignitz-Ruppin, Brandenburg"},
            {"OR", "Oranienburg, Brandenburg"},
            {"OS", "Osnabrück, Lower Saxony"},
            {"OSL", "Oberspreewald-Lausitz, Brandenburg"},
            {"OTT", "Otterndorf, Lower Saxony"},
            {"OTW", "Ottweiler, Saarland"},
            {"OVI", "Oberviechtach, Bavaria"},
            {"OVL", "Obervogtland, Saxony"},
            {"OVP", "Ostvorpommern, Mecklenburg-Vorpommern"},
            {"OZ", "Oschatz, Saxony"},
            {"P", "Potsdam, Brandenburg"},
            {"PA", "Passau, Bavaria"},
            {"PAF", "Pfaffenhofen an der Ilm, Bavaria"},
            {"PAN", "Pfarrkirchen & Rottal-Inn, Bavaria"},
            {"PAR", "Parsberg, Bavaria"},
            {"PB", "Paderborn, North-Rhine-Westphalia"},
            {"PCH", "Parchim, Mecklenburg-Vorpommern"},
            {"PE", "Peine, Lower Saxony"},
            {"PEG", "Pegnitz, Bavraia"},
            {"PER", "Perleberg, Brandenburg"},
            {"PF", "Pforzheim & Enzkreis, Baden-Württemberg"},
            {"PI", "Pinneberg, Schleswig-Holstein"},
            {"PIR", "Pirna, Saxony"},
            {"PK", "Pritzwalk, Brandenburg"},
            {"PL", "Plauen, Saxony"},
            {"PLÖ", "Plön, Schleswig-Holstein"},
            {"PM", "Potsdam-Mittelmark, Brandenburg"},
            {"PN", "Pößneck, Thuringia"},
            {"PR", "Prignitz, Brandenburg"},
            {"PRÜ", "Prüm, Rhineland Palatinate"},
            {"PS", "Pirmasens & Südwestpfalz, Rhineland Palatinate"},
            {"PW", "Pasewalk, Mecklenburg-Vorpommern"},
            {"PZ", "Prenzlau, Brandenburg"},
            {"QFT", "Querfurt, Saxony Anhalt"},
            {"QLB", "Quedlinburg, Saxony-Anhalt"},
            {"R", "Regensberg, Bavaria"},
            {"RA", "Ratstatt, Baden-Württemberg"},
            {"RC", "Reichenbach, Saxony"},
            {"RD", "Rendsburg-Eckernförde, Schleswig-Holstein"},
            {"RDG", "Ribnitz-Damgarten, Mecklenburg-Vorpommern"},
            {"RE", "Recklinghausen, North-Rhine-Westphalia"},
            {"REG", "Regen, Bavaria"},
            {"REH", "Rehau, Bavaria"},
            {"REI", "Bad Reichenhall, Bavaria"},
            {"RG", "Riesa-Großenhain, Saxony"},
            {"RH", "Roth bei Nürnberg, Bavaria"},
            {"RI", "Rinteln, Lower Saxony"},
            {"RID", "Riedenburg, Bavaria"},
            {"RIE", "Riesa, Saxony"},
            {"RL", "Rochlitz, Saxony"},
            {"RM", "Röbel/Muritz, Mecklenburg-Vorpommern"},
            {"RN", "Rathenow, Brandenburg"},
            {"RO", "Rosenheim, Bavaria"},
            {"ROD", "Roding, Bavaria"},
            {"ROF", "Rotenburg bei Fulda, Hesse"},
            {"ROH", "Rotenburg Wümme, Lower Saxony"},
            {"ROK", "Rockenhausen, Rhineland Palatinate"},
            {"ROL", "Rottenburg Laaber, Bavaria"},
            {"ROS", "Rostock Land, Mecklenburg-Vorpommern"},
            {"ROT", "Rothenburg ob der Tauber, Bavaria"},
            {"ROW", "Rotenburg (Wümme) & Bremervörde, Lower Saxony"},
            {"RPL", "Rhineland Palatinate State official vehicles"},
            {"RS", "Remscheid, North-Rhine-Westphalia"},
            {"RSL", "Roßlau, Saxony Anhalt"},
            {"RT", "Reutlingen, Baden-Württemberg"},
            {"RU", "Rudolstadt"},
            {"RÜD", "Rüdesheim & Rheingau-Taunus-Kreis, Hesse"},
            {"RÜG", "Rügen, Mecklenburg-Vorpommern"},
            {"RV", "Ravensburg, Baden-Württemberg"},
            {"RW", "Rottweil, Baden-Württemberg"},
            {"RWL", "North-Rhine-Westphalia State official vehicles"},
            {"RY", "Rheydt, North-Rhine-Westphalia"},
            {"RZ", "Ratzeburg & Hertzogtum Lauenburg, Schleswig-Holstein"},
            {"S", "Stuttgart, Baden-Württemberg"},
            {"SAB", "Saarburg, Rhineland Palatinate"},
            {"SAD", "Schwandorf, Bavaria"},
            {"SÄK", "Säckingen, Baden-Württemberg"},
            {"SAL", "Saarland official vehicles"},
            {"SAN", "Stadtsteinach, Bavaria"},
            {"SAO", "Saale-Orla Kreis"},
            {"SAW", "Altmarkkreis Salzwedel, Saxony-Anhalt"},
            {"SB", "Saarbrücken, Saarland"},
            {"SBG", "Strasburg, Mecklenburg-Vorpommern"},
            {"SBK", "Schönebeck, Saxony-Anhalt"},
            {"SC", "Schwabach, Bavaria"},
            {"SCZ", "Schleiz, Thuringia"},
            {"SDH", "Sondershausen, Thuringia"},
            {"SDL", "Stendal, Saxony-Anhalt"},
            {"SDT", "Schwedt, Brandenburg"},
            {"SE", "Segeberg, Schleswig-Holstein"},
            {"SEB", "Sebnitz, Saxony"},
            {"SEE", "Seelow, Brandenburg"},
            {"SEF", "Scheinfeld, Bavaria"},
            {"SEL", "Selb, Bavaria"},
            {"SF", "Sonthofen, Bavaria"},
            {"SFA", "Soltau-Fallingbostel, Lower Saxony"},
            {"SFB", "Senftenberg, Brandenburg"},
            {"SFT", "Staßfurt, Saxony Anhalt"},
            {"SG", "Solingen, North-Rhine-Westphalia"},
            {"SGH", "Sangerhausen, Saxony-Anhalt"},
            {"SH", "Schleswig-Holstein Land official vehicles"},
            {"SHA", "Schwäbisch Hall, Baden-Württemberg"},
            {"SHG", "Stadthagen & Schaumburg, Lower Saxony"},
            {"SHK", "Saale-Holzland-Kreis, Thuringia"},
            {"SHL", "Suhl, Thuringia"},
            {"SHS", "Sangerhausen"},
            {"SI", "Siegen-Wittgenstein, North-Rhine-Westphalia"},
            {"SIG", "Sigmaringen, Baden-Württemberg"},
            {"SIM", "Simmern & Rhein-Hunsrück-Kreis, Rhineland Palatinate"},
            {"SK", "Saalkreis, Saxony-Anhalt"},
            {"SL", "Schleswig-Flensburg, Schleswig-Holstein"},
            {"SLE", "Schleiden (Eifel), North-Rhine-Westphalia"},
            {"SLF", "Saalfeld-Rudolstadt, Thuringia"},
            {"SLG", "Saulgau, Baden-Württemberg"},
            {"SLK", "Salzlandkreis, Saxony-Anhalt"},
            {"SLN", "Schmölin, Thuringia"},
            {"SLS", "Saarlouis, Saarland"},
            {"SLÜ", "Schlüchtern, Hesse"},
            {"SLZ", "Bad Salzungen, Thuringia"},
            {"SM", "Schmalkalden-Meiningen, Thuringia"},
            {"SMÜ", "Schwabmünchen, Bavaria"},
            {"SN", "Schwerin, Mecklenburg-Vorpommern"},
            {"SNH", "Sinsheim, Baden-Württemberg"},
            {"SO", "Soest, North-Rhine-Westphalia"},
            {"SOB", "Schrobenhausen, Bavaria"},
            {"SOG", "Schongau, Bavaria"},
            {"SOK", "Saale-Orla-Kreis, Thuringia"},
            {"SOL", "Soltau, Lower Saxony"},
            {"SÖM", "Sömmerda, Thuringia"},
            {"SON", "Sonneberg, Thuringia"},
            {"SP", "Speyer, Rhineland Palatinate"},
            {"SPB", "Spremberg, Brandenburg"},
            {"SPN", "Spree-Neiße, Brandenburg"},
            {"SPR", "Springe, Lower Saxony"},
            {"SR", "Straubing & Straubing-Bogen, Bavaria"},
            {"SRB", "Strausberg, Brandenburg"},
            {"SRO", "Stadtroda, Thuringia"},
            {"ST", "Steinfurt, North-Rhine-Westphalia"},
            {"STA", "Starnberg, Bavaria"},
            {"STB", "Sternberg, Mecklenburg-Vorpommern"},
            {"STD", "Stade, Lower Saxony"},
            {"STE", "Staffelstein, Bavaria"},
            {"STH", "Stadthagen, Lower Saxony"},
            {"STL", "Stollberg, Saxony"},
            {"STO", "Stockach, Baden-Württemberg"},
            {"SU", "Siegburg & Rhein-Sieg-Kreis, North-Rhine-Westphalia"},
            {"SUL", "Sulzbach-Rosenberg, Bavaria"},
            {"SÜW", "Südliche Weinstraße, Rhineland Palatinate"},
            {"SW", "Schweinfurt, Bavaria"},
            {"SWA", "Bad Schwalbach & Rheingau-Taunus-Kreis, Hesse"},
            {"SWZ", "Schwarzakreis"},
            {"SY", "Syke, Lower Saxony"},
            {"SZ", "Salzgitter, Lower Saxony"},
            {"SZB", "Schwarzenberg, Saxony"},
            {"TBB", "Tauberbischofsheim & Main-Tauber-Kreis, Baden-Württemberg"},
            {"TE", "Teterow, Mecklenburg-Vorpommern"},
            {"TF", "Teltow-Fläming, Brandenburg"},
            {"TG", "Torgau, Saxony"},
            {"TGO", "Thurgau-Oschatz"},
            {"THL", "Thuringia State (Thüringen Land) official vehicles"},
            {"THW", "German Federal Agency for Technical Relief vehicles"},
            {"TIR", "Tirschenreuth, Bavaria"},
            {"TO", "Torgau-Oschatz, Saxony"},
            {"TÖL", "Bad Tölz-Wolfratshausen, Bavaria"},
            {"TÖN", "Tönning, Schleswig-Holstein"},
            {"TP", "Templin, Brandenburg"},
            {"TR", "Trier, Rhineland Palatinate"},
            {"TS", "Traunstein, Bavaria"},
            {"TT", "Tettnang, Baden-Württemberg"},
            {"TÜ", "Tübingen, Baden-Württemberg"},
            {"TUT", "Tuttlingen, Baden-Württemberg"},
            {"ÜB", "Überlingen, Baden-Württemberg"},
            {"UE", "Uelzen, Lower Saxony"},
            {"UEM", "Ueckermünde, Mecklenburg-Vorpommern"},
            {"UER", "Uecker-Randow, Mecklenburg-Vorpommern"},
            {"UFF", "Uffenheim, Bavaria"},
            {"UH", "Unstrut-Hainich, Thuringia"},
            {"UL", "Ulm & Alb-Donau-Kreis, Baden-Württemberg"},
            {"UM", "Uckermark, Brandenburg"},
            {"UN", "Unna, North-Rhine-Westphalia"},
            {"USI", "Usingen, Hesse"},
            {"V", "Vogtlandkreis, Saxony"},
            {"VAI", "Vaihingen, Baden-Württemberg"},
            {"VB", "Vogelsbergkreis, Hesse"},
            {"VEC", "Vechta, Lower Saxony"},
            {"VER", "Verden, Lower Saxony"},
            {"VIB", "Vilsbiburg, Bavaria"},
            {"VIE", "Viersen, North-Rhine-Westphalia"},
            {"VIT", "Viechtach, Bavaria"},
            {"VK", "Völklingen, Saarland"},
            {"VL", "Villingen, Baden-Württemberg"},
            {"VOF", "Vilshofen, Bavaria"},
            {"VOH", "Vohenstrauß, Bavaria"},
            {"VR", "Vorpommern-Rügen, Mecklenburg-Vorpommern"},
            {"VS", "Villingen-Schwenningen & Schwarzwald-Baar-Kreis, Baden-Württemberg"},
            {"W", "Wuppertal, North-Rhine-Westphalia"},
            {"WA", "Waldeck, Hesse"},
            {"WAF", "Kreis Warendorf, North-Rhine-Westphalia"},
            {"WAK", "Wartburgkreis, Thuringia"},
            {"WAM", "Westliche Altmark"},
            {"WAN", "Wanne-Eickel, North-Rhine-Westphalia"},
            {"WAR", "Warburg, North-Rhine-Westphalia"},
            {"WAT", "Wattenscheid, North-Rhine-Westphalia"},
            {"WB", "Wittenberg, Saxony-Anhalt"},
            {"WBS", "Worbis, Thuringia"},
            {"WD", "Weidenbrück, North-Rhine-Westphalia"},
            {"WDA", "Werdau, Saxony"},
            {"WE", "Weimar, Thuringia"},
            {"WEB", "Westerburg, Rhineland Palatinate"},
            {"WEG", "Wegscheid, Bavaria"},
            {"WEI", "Weimarer Land (Kreis Apolda)"},
            {"WEL", "Weilburg, Hesse"},
            {"WEM", "Wesermünde, Lower Saxony"},
            {"WEN", "Weiden in der Oberpfalz, Bavaria"},
            {"WER", "Wertingen, Bavaria"},
            {"WES", "Wesel, North-Rhine-Westphalia"},
            {"WF", "Wolfenbüttel, Lower Saxony"},
            {"WG", "Wangen, Baden-Württemberg"},
            {"WHV", "Wilhelmshaven, Lower Saxony"},
            {"WI", "Wiesbaden, Hesse"},
            {"WIL", "Wittlich & Bernkastel-Wittlich, Rhineland Palatinate"},
            {"WIS", "Wismarer Land"},
            {"WIT", "Witten, North-Rhine-Westphalia"},
            {"WIZ", "Witzenhausen, Hesse"},
            {"WK", "Wittstock, Brandenburg"},
            {"WL", "Winsen (Luhe) & Harburg, Lower Saxony"},
            {"WLG", "Wolgast, Mecklenburg-Vorpommern"},
            {"WM", "Weilheim-Schongau, Bavaria"},
            {"WMS", "Wolmirstedt, Saxony Anhalt"},
            {"WN", "Waiblingen & Rems-Murr-Kreis, Baden-Württemberg"},
            {"WND", "St Wendel, Saarland"},
            {"WO", "Worms, Rhineland Palatinate"},
            {"WOB", "Wolfsburg, Lower Saxony"},
            {"WOH", "Wolfhagen, Hesse"},
            {"WOL", "Wolfach, Baden-Württemberg"},
            {"WOR", "Wolfratshausen, Bavaria"},
            {"WOS", "Wolfstein, Bavaria"},
            {"WR", "Wernigerode, Saxony-Anhalt"},
            {"WRN", "Waren, Mecklenburg-Vorpommern"},
            {"WS", "Wasserburg, Bavaria"},
            {"WSF", "Weißenfels, Saxony-Anhalt"},
            {"WST", "Westerstede & Ammerland, Lower Saxony"},
            {"WSW", "Weißwasser, Saxony"},
            {"WT", "Waldshut, Baden-Württemberg"},
            {"WTL", "Wittlage, Lower Saxony"},
            {"WTM", "Wittmund, Lower Saxony"},
            {"WÜ", "Würzburg, Bavaria"},
            {"WUG", "Weißenburg-Gunzenhausen, Bavaria"},
            {"WUM", "Waldmünchen, Bavaria"},
            {"WUN", "Wunsiedel am Fichtelgebirge, Bavaria"},
            {"WUR", "Wurzen, Saxony"},
            {"WW", "Westerwaldkreis, Rhineland Palatinate"},
            {"WZ", "Wetzlar, Hesse"},
            {"WZL", "Wanzleben, Saxony Anhalt"},
            {"X", "NATO Forces vehicles"},
            {"Y", "Armed Forces vehicles"},
            {"Z", "Zwickauer Land, Saxony"},
            {"ZE", "Zerbst, Saxony-Anhalt"},
            {"ZEL", "Zell, Rhineland Palatinate"},
            {"ZI", "Löbau-Zittau"},
            {"ZIG", "Ziegenhain, Hesse"},
            {"ZP", "Zschopau, Saxony"},
            {"ZR", "Zeulenroda, Thuringia"},
            {"ZS", "Zossen, Brandenburg"},
            {"ZW", "Zweibrücken, Rhineland Palatinate"},
            {"ZZ", "Zeitz, Saxony Anhalt"}
        };
    }
}